[build]
builder = "nixpacks"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10

[deploy.healthcheck]
path = "/api/health"
interval = "30s"
timeout = "10s"
retries = 3
